### ISSUE TITLE
Webpack unable to resolve font files

### ISSUE THREAD

**Issue by jimboslicethat** [KyleAMathews/typefaces#48]
Hey there! I'm getting started with `material-ui` and trying to get `typeface-roboto` added to my build process for self hosting.

I've tried using webpack `file-loader` & `url-loader`, with every possible configuration option I can think of, and I still can't get webpack to resolve these font files.

Since this project runs on the assumption that users will be using webpack as their build tool, I think it would be advantageous to provide documentation on the appropriate webpack configuration for `woff` files in the README.

Here is my current configuration:
```
{
    test: /\.(woff|woff2|eot|ttf)$/,
    use: [
       { loader: 'file-loader' }
     ]
}
```

It could be that I'm missing something basic. I will admit webpack is not my forte. I ended up here because the [Material Design Documentation](https://material-ui-next.com/style/typography/#general) points back to the typefaces project. Can also see the following [issue](https://github.com/mui-org/material-ui/issues/6256) in material-ui

**Comment by alebianco** [comment]
The problem started in release 0.0.46 because the "files" folder, which contains the actual font files, disappeared.

Revert to 0.0.45 while they fix this ...

**Comment by damianobarbati** [comment]
@alebianco I noted the same: there's no build script in package.json I see

**Comment by KyleAMathews** [comment]
Looks like we got bit by this — https://github.com/npm/npm/issues/18461

Updated my NPM to 2.6.0 and it's publishing the files directory again.

Which packages did people have trouble with other than Roboto?

**Comment by callmemagnus** [comment]
typeface-fira-sans is missing the files directory too. Can you release that one too?

**Comment by KyleAMathews** [comment]
Pushed new version of typeface-fira-sans

**Comment by grigored** [comment]
import 'typeface-roboto' should be discouraged as (at least in my webpack configuration) it greatly increases the bundle size (from 400kb gziped to about 1.6mb gzipped) and does not take advantage of caching (most users probably already have roboto cached in their browser).

**Comment by KyleAMathews** [comment]
@grigored no idea how your bundle size would increase so much. I suspect you have something wrong with your webpack config. Perhaps you're inlining font files in the JS bundle.

**Comment by alebianco** [comment]
@grigored thanks but that's not what the issue is about.
I do want the fonts to be bundled and I surely don't want to load a stylesheet from the network. Whether you want the same or not depends on your project and not on the ability of doing it or not.

**Comment by jimboslicethat** [comment]
Sorry I haven't had the time to look at this quite yet. Tonight I will try bumping down to `0.0.45` and update on whether or not that worked for me.

I am curious though.... what _**should**_ my bundle size increase by assuming my webpack config stays more or less the same as my example above?

**Comment by KyleAMathews** [comment]
Perhaps you're I lining the font files into your bundle instead of copying them to your public directory

**Comment by grigored** [comment]
@KyleAMathews thanks for your quick replies. I don't have any public directory, all i have is one bundle.

**Comment by jimboslicethat** [comment]
Hey @KyleAMathews. Id just like to give a quick update: 
I tried upgrading to the latest version `(0.0.50)`, and downgrading to `(0.0.45)` as @alebianco has suggested. Neither version has worked for me. I am still getting:
```
ERROR in ./node_modules/css-loader?{"modules":true,"localIdentName":"[path][name]__[local]--[hash:base64:5]"}!./node_modules/postcss-loader/lib!./node_modules/typeface-roboto/index.css
Module not found: Error: Can't resolve 'files/roboto-latin-100.woff' in '/Users/jameswalsh/dev/indv/nat-twenty-io/client/node_modules/typeface-roboto'
 @ ./node_modules/css-loader?{"modules":true,"localIdentName":"[path][name]__[local]--[hash:base64:5]"}!./node_modules/postcss-loader/lib!./node_modules/typeface-roboto/index.css 6:316-354
 @ ./node_modules/typeface-roboto/index.css
 @ ./src/index.js
```

My webpack config is still the same as my earlier post. I still feel as though a README update with webpack instructions would be beneficial to the larger community. Any suggestions on what I can try from here would be greatly appreciated. Thank you for your help in advance!

**Comment by whmountains** [comment]
`typeface-spectral` is also missing the files.

**Comment by loganpowell** [comment]
@jimboslicethat I'm also getting this, but with `roboto`:

```
./node_modules/typeface-lora/index.css
Module not found: Can't resolve './files/lora-latin-400.woff' in 'C:\Users\surface\Projects\Bootcamp\census\graphql\RAATS\node_modules\typeface-lora'
```

I'm using `react-app-rewired` could that be the issue?

**Comment by KyleAMathews** [comment]
I just republished all google font files so this should be fixed 👍 

Thanks for the bug report!

**Comment by jimboslicethat** [comment]
@KyleAMathews thanks for doing that! I bumped my version and I do see the `files` directory. However I believe my issue may be related to webpack, as I'm still getting the error I reported earlier. I do think it would be a good idea to create some documentation around what an appropriate webpack configuration looks like to consume typefaces. Im currently trying to use `file-loader`, but haven't been successful. I could be missing something basic, but I'm open to suggestions.

**Comment by KyleAMathews** [comment]
I'd love to see a PR adding docs for a simple webpack config. If you can though, I'd recommend using something like Gatsby or CRA which sets webpack up for you as Typefaces works out of the box with both of those.

**Comment by 3DEsprit** [comment]
As much as I hated to do it, I was in a rush, and I used a relative import to make this work:

```
@import '../../node_modules/typeface-roboto/index.css';  /* assuming importing css file is two levels deep */
```

I am going through a transition from sass to css-in-js, so I'm sure that's not helping. I will test a pure import after that's complete assuming there is still a lack of a custom Webpack configuration solution (as it seems to stand).
